#+SETUPFILE: /home/zyd/Downloads/util/org-html-themes-master/org/theme-readtheorg.setup 

* Learn HtmlCssJavascript(HCJ) by doing


** introduction

In this notes, we proposed a learning path for HCJ. The idea is to repeat the loop of "creating page-deploy/test-learn new featuresa and improve page-deploy/test again-...". In each step, some new features learned will added to the page, then the page will be deployed and tested. By this way, features of HCJ are learned by practicing gradually.  

** minmial page
The pagesindex.html is located in the directory:
/home/zyd/projects/hcj/c1/hcj_test/site

Also, it can be syncnized with the github page by using below command:
git add .
git commit
git push

*** the page url

1. goto repository and click the settings button
2. Or use
https://github.com/TT1232/hcj_test/settings/pages
3. Then we can find page test link is:
https://tt1232.github.io/hcj_test/site/




** convert org mode file into html

** browser-sync
By using the browser-sync, we can debug the html page locally
easily. When the html page is changed, the contents in the browser
will change automatically.

The command is:
browser-sync start --server --directory --files "*"   

The above command need to be used in the same directory where the html
file is.
